# Generated on Mon Aug 12 16:09:56 EDT 2019
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-service
spec:
  selector:
    matchLabels:
      app: fortune-service
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune-service
    spec:
      containers:
        - name: fortune-service
          image: docker.io/ciberkleid/fortune-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
          imagePullPolicy: Always
          ports:
            - containerPort: 8080