# Generated on Mon Aug 12 16:09:56 EDT 2019
kind: Service
apiVersion: v1
metadata:
  name: fortune-service
  labels:
    app: fortune-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: fortune-service
  selector:
    app: fortune-service